ARTIFACTS_DIR: "artifacts"
MODEL:
  in_ch: 1
  base_ch: 64
  group_norm_ch: 32
  ch_scalings: [1, 2, 4]
  t_dim: 256
  T: 1000
  beta_1: 0.0001
  beta_T: 0.02
  num_classes: 10
  class_drop_prob: 0.2
DATA:
  dataset: MNISTDataset
  root_dir: "data/mnist"
  batch_size: 32
  img_size: [1, 32, 32]
MISC:
  n_denoise_imgs: 1
  plot_every_t_steps: 100
OPTIM:
  optimizer: "AdamW"
  lr: 0.0002
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  max_eval_iters: 25
  save_ckpt_every: 5
  eval_every: 1
  gradient_clip: null
  scheduler: "cosine"
  T_max: 100
  eta_min: 0.00001
