ARTIFACTS_DIR: "artifacts"
MODEL:
  model_class: ResNet18
  pretrained: false
LSS:
  depth_config:
    d_min: 4
    d_max: 45
    d_step: 1
  bev_config:
    x_min: -25
    x_max: 25
    y_min: 0
    y_max: 50
    cell_size: 0.5
DATA:
  dataset: NuScenesDataset
  root_dir: "data/nuscenes/v1.0-mini"
  splits:
    train:
      [
        "scene-0061",
        "scene-0553",
        "scene-0655",
        "scene-0757",
        "scene-0796",
        "scene-1077",
        "scene-1094",
        "scene-1100",
      ]
    val: ["scene-0103", "scene-0916"]
OPTIM:
  optimizer: "AdamW"
  lr: 0.0002
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  batch_size: 1
  max_eval_iters: 25
  save_ckpt_every: -1
  eval_every: 1
  gradient_clip: null
  scheduler: "cosine"
  T_max: 100
  eta_min: 0.00001
